.TH shellcuts 1 "2 September 2019" "1.3.0"

.SH NAME
shellcuts - directory shortcuts for your shell.

.SH SYNOPSIS
.RS 0
.B sc
.RI [ shellcut ]
.RE
.RS 0
.B sc
.I option
.RI [ shellcut
.RI [ follow ]]
.RE

.SH DESCRIPTION
Shellcuts allows you to jump between saved locations in your filesystem via a single, short command. Shellcuts can:
.PP
.RS 2
- create a named shellcut for any location in your filesystem
.RE
.RS 2
- add a follow-up command to any shellcut like
.I ls
or
.I clear
.RE
.RS 2
- save a temporary "bread crumb" shellcut
.RE
.RS 2
- delete any shellcut by name
.RE
.RS 2
- list all available shellcuts
.RE

.SH OPTIONS
.PP
.B -n, --new
.I shellcut follow
.RS 4
create a new shellcut for the current directory with an optional follow up command
.RE
.PP
.B -m, --move
.I shellcut
.RS 4
move an existing shellcut to a new directory
.RE
.PP
.B  -d, --delete 
.I shellcut
.RS 4
delete the specified shellcut if it exists
.RE
.PP
.B -p, --print
.I shellcut
.RS 4
print the specified shellcut to the screen
.RE
.PP
.B -f, --follow
.I shellcut follow
.RS 4
add a follow up command that executes after each jump to a particular shellcut
.RE
.PP
.B -l, --list
.RS 4
list all available shellcuts
.RE
.PP
.B -c, --crumb
.RS 4
create a temporary bread crumb that can be jumped to via
.I sc
alone
.RE
.PP
.B -h, --help
.RS 4
display a help menu for quick reference
.RE
.PP
.B -u, --unfollow
.I shellcut
.RS 4
remove a follow up command from a particular shellcut
.RE
.PP
.B -v, --version
.RS 4
display version information
.RE
.PP
.B --man
.RS 4
display this manual page
.RE

.SH EXAMPLES
Save a shellcut named
.I downloads
using the user's current directory:
.RS 4
.B sc -n downloads
.RE
.PP
Go to the shellcut named
.I downloads
if it exists:
.RS 4
.B sc downloads
.RE
.PP
List all saved shellcuts:
.RS 4
.B sc -l
.RE
.PP
Delete a shellcut named
.I binaries
if it exists:
.RS 4
.B sc -d binaries
.RE
.PP
Print a shellcut named
.I home
if it exists:
.RS 4
.B sc -p home
.RE
.PP
Save the current directory as a bread crumb:
.RS 4
.B sc -c
.RE
.PP
Jump to the most recent bread crumb:
.RS 4
.B sc
.RE
.PP
Save a new shellcut named
.I home
with the
.I clear
follow command:
.RS 4
.B sc -n home clear
.RE
.PP
Add the
.I ls
follow command to the existing
.I downloads
shellcut:
.RS 4
.B sc -f downloads ls
.RE
.PP
Remove the
.I ls
command from the
.I downloads
shellcut:
.RS 4
.B sc --unfollow downloads
.RE
.PP

.SH FILES
.B ~/.shellcuts/
.RS 4
contains all program files
.RE
.B ~/.shellcuts/docs/
.RS 4
location of all documentation
.RE
.B ~/.shellcuts/source/
.RS 4
contains all Python source code for Shellcuts
.RE
.B ~/.shellcuts/data/shellcuts.json
.RS 4
contains all shellcuts in the JSON format
.RE
.B ~/.shellcuts/data/variables.json
.RS 4
contains all variables and settings for Shellcuts
.RE

.SH LICENSE
MIT

.SH SOURCE
Visit
.I https://www.github.com/tgsachse/shellcuts
to view the complete project and give the repository a star if you really liked it!

.SH AUTHOR
Tiger Sachse (tgsachse)
